/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cast_channel.proto */

#ifndef PROTOBUF_C_cast_5fchannel_2eproto__INCLUDED
#define PROTOBUF_C_cast_5fchannel_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1003000
# error This file was generated by a newer version of protobuf-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1005001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protobuf-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protobuf-c.
#endif


typedef struct CastChannel__CastMessage CastChannel__CastMessage;
typedef struct CastChannel__AuthChallenge CastChannel__AuthChallenge;
typedef struct CastChannel__AuthResponse CastChannel__AuthResponse;
typedef struct CastChannel__AuthError CastChannel__AuthError;
typedef struct CastChannel__DeviceAuthMessage CastChannel__DeviceAuthMessage;


/* --- enums --- */

typedef enum _CastChannel__CastMessage__ProtocolVersion {
  CAST_CHANNEL__CAST_MESSAGE__PROTOCOL_VERSION__CASTV2_1_0 = 0
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAST_CHANNEL__CAST_MESSAGE__PROTOCOL_VERSION)
} CastChannel__CastMessage__ProtocolVersion;
typedef enum _CastChannel__CastMessage__PayloadType {
  CAST_CHANNEL__CAST_MESSAGE__PAYLOAD_TYPE__STRING = 0,
  CAST_CHANNEL__CAST_MESSAGE__PAYLOAD_TYPE__BINARY = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAST_CHANNEL__CAST_MESSAGE__PAYLOAD_TYPE)
} CastChannel__CastMessage__PayloadType;
typedef enum _CastChannel__AuthError__ErrorType {
  CAST_CHANNEL__AUTH_ERROR__ERROR_TYPE__INTERNAL_ERROR = 0,
  CAST_CHANNEL__AUTH_ERROR__ERROR_TYPE__NO_TLS = 1
    PROTOBUF_C__FORCE_ENUM_TO_BE_INT_SIZE(CAST_CHANNEL__AUTH_ERROR__ERROR_TYPE)
} CastChannel__AuthError__ErrorType;

/* --- messages --- */

struct  CastChannel__CastMessage
{
  ProtobufCMessage base;
  CastChannel__CastMessage__ProtocolVersion protocol_version;
  char *source_id;
  char *destination_id;
  char *namespace_;
  CastChannel__CastMessage__PayloadType payload_type;
  char *payload_utf8;
  protobuf_c_boolean has_payload_binary;
  ProtobufCBinaryData payload_binary;
};
#define CAST_CHANNEL__CAST_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cast_channel__cast_message__descriptor) \
    , CAST_CHANNEL__CAST_MESSAGE__PROTOCOL_VERSION__CASTV2_1_0, NULL, NULL, NULL, CAST_CHANNEL__CAST_MESSAGE__PAYLOAD_TYPE__STRING, NULL, 0, {0,NULL} }


struct  CastChannel__AuthChallenge
{
  ProtobufCMessage base;
};
#define CAST_CHANNEL__AUTH_CHALLENGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cast_channel__auth_challenge__descriptor) \
     }


struct  CastChannel__AuthResponse
{
  ProtobufCMessage base;
  ProtobufCBinaryData signature;
  ProtobufCBinaryData client_auth_certificate;
  size_t n_client_ca;
  ProtobufCBinaryData *client_ca;
};
#define CAST_CHANNEL__AUTH_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cast_channel__auth_response__descriptor) \
    , {0,NULL}, {0,NULL}, 0,NULL }


struct  CastChannel__AuthError
{
  ProtobufCMessage base;
  CastChannel__AuthError__ErrorType error_type;
};
#define CAST_CHANNEL__AUTH_ERROR__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cast_channel__auth_error__descriptor) \
    , CAST_CHANNEL__AUTH_ERROR__ERROR_TYPE__INTERNAL_ERROR }


struct  CastChannel__DeviceAuthMessage
{
  ProtobufCMessage base;
  CastChannel__AuthChallenge *challenge;
  CastChannel__AuthResponse *response;
  CastChannel__AuthError *error;
};
#define CAST_CHANNEL__DEVICE_AUTH_MESSAGE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&cast_channel__device_auth_message__descriptor) \
    , NULL, NULL, NULL }


/* CastChannel__CastMessage methods */
void   cast_channel__cast_message__init
                     (CastChannel__CastMessage         *message);
size_t cast_channel__cast_message__get_packed_size
                     (const CastChannel__CastMessage   *message);
size_t cast_channel__cast_message__pack
                     (const CastChannel__CastMessage   *message,
                      uint8_t             *out);
size_t cast_channel__cast_message__pack_to_buffer
                     (const CastChannel__CastMessage   *message,
                      ProtobufCBuffer     *buffer);
CastChannel__CastMessage *
       cast_channel__cast_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cast_channel__cast_message__free_unpacked
                     (CastChannel__CastMessage *message,
                      ProtobufCAllocator *allocator);
/* CastChannel__AuthChallenge methods */
void   cast_channel__auth_challenge__init
                     (CastChannel__AuthChallenge         *message);
size_t cast_channel__auth_challenge__get_packed_size
                     (const CastChannel__AuthChallenge   *message);
size_t cast_channel__auth_challenge__pack
                     (const CastChannel__AuthChallenge   *message,
                      uint8_t             *out);
size_t cast_channel__auth_challenge__pack_to_buffer
                     (const CastChannel__AuthChallenge   *message,
                      ProtobufCBuffer     *buffer);
CastChannel__AuthChallenge *
       cast_channel__auth_challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cast_channel__auth_challenge__free_unpacked
                     (CastChannel__AuthChallenge *message,
                      ProtobufCAllocator *allocator);
/* CastChannel__AuthResponse methods */
void   cast_channel__auth_response__init
                     (CastChannel__AuthResponse         *message);
size_t cast_channel__auth_response__get_packed_size
                     (const CastChannel__AuthResponse   *message);
size_t cast_channel__auth_response__pack
                     (const CastChannel__AuthResponse   *message,
                      uint8_t             *out);
size_t cast_channel__auth_response__pack_to_buffer
                     (const CastChannel__AuthResponse   *message,
                      ProtobufCBuffer     *buffer);
CastChannel__AuthResponse *
       cast_channel__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cast_channel__auth_response__free_unpacked
                     (CastChannel__AuthResponse *message,
                      ProtobufCAllocator *allocator);
/* CastChannel__AuthError methods */
void   cast_channel__auth_error__init
                     (CastChannel__AuthError         *message);
size_t cast_channel__auth_error__get_packed_size
                     (const CastChannel__AuthError   *message);
size_t cast_channel__auth_error__pack
                     (const CastChannel__AuthError   *message,
                      uint8_t             *out);
size_t cast_channel__auth_error__pack_to_buffer
                     (const CastChannel__AuthError   *message,
                      ProtobufCBuffer     *buffer);
CastChannel__AuthError *
       cast_channel__auth_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cast_channel__auth_error__free_unpacked
                     (CastChannel__AuthError *message,
                      ProtobufCAllocator *allocator);
/* CastChannel__DeviceAuthMessage methods */
void   cast_channel__device_auth_message__init
                     (CastChannel__DeviceAuthMessage         *message);
size_t cast_channel__device_auth_message__get_packed_size
                     (const CastChannel__DeviceAuthMessage   *message);
size_t cast_channel__device_auth_message__pack
                     (const CastChannel__DeviceAuthMessage   *message,
                      uint8_t             *out);
size_t cast_channel__device_auth_message__pack_to_buffer
                     (const CastChannel__DeviceAuthMessage   *message,
                      ProtobufCBuffer     *buffer);
CastChannel__DeviceAuthMessage *
       cast_channel__device_auth_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   cast_channel__device_auth_message__free_unpacked
                     (CastChannel__DeviceAuthMessage *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*CastChannel__CastMessage_Closure)
                 (const CastChannel__CastMessage *message,
                  void *closure_data);
typedef void (*CastChannel__AuthChallenge_Closure)
                 (const CastChannel__AuthChallenge *message,
                  void *closure_data);
typedef void (*CastChannel__AuthResponse_Closure)
                 (const CastChannel__AuthResponse *message,
                  void *closure_data);
typedef void (*CastChannel__AuthError_Closure)
                 (const CastChannel__AuthError *message,
                  void *closure_data);
typedef void (*CastChannel__DeviceAuthMessage_Closure)
                 (const CastChannel__DeviceAuthMessage *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor cast_channel__cast_message__descriptor;
extern const ProtobufCEnumDescriptor    cast_channel__cast_message__protocol_version__descriptor;
extern const ProtobufCEnumDescriptor    cast_channel__cast_message__payload_type__descriptor;
extern const ProtobufCMessageDescriptor cast_channel__auth_challenge__descriptor;
extern const ProtobufCMessageDescriptor cast_channel__auth_response__descriptor;
extern const ProtobufCMessageDescriptor cast_channel__auth_error__descriptor;
extern const ProtobufCEnumDescriptor    cast_channel__auth_error__error_type__descriptor;
extern const ProtobufCMessageDescriptor cast_channel__device_auth_message__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_cast_5fchannel_2eproto__INCLUDED */
