/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: cast_channel.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "cast_channel.pb-c.h"
void   cast_channel__cast_message__init
                     (CastChannel__CastMessage         *message)
{
  static const CastChannel__CastMessage init_value = CAST_CHANNEL__CAST_MESSAGE__INIT;
  *message = init_value;
}
size_t cast_channel__cast_message__get_packed_size
                     (const CastChannel__CastMessage *message)
{
  assert(message->base.descriptor == &cast_channel__cast_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cast_channel__cast_message__pack
                     (const CastChannel__CastMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cast_channel__cast_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cast_channel__cast_message__pack_to_buffer
                     (const CastChannel__CastMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cast_channel__cast_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CastChannel__CastMessage *
       cast_channel__cast_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CastChannel__CastMessage *)
     protobuf_c_message_unpack (&cast_channel__cast_message__descriptor,
                                allocator, len, data);
}
void   cast_channel__cast_message__free_unpacked
                     (CastChannel__CastMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cast_channel__cast_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cast_channel__auth_challenge__init
                     (CastChannel__AuthChallenge         *message)
{
  static const CastChannel__AuthChallenge init_value = CAST_CHANNEL__AUTH_CHALLENGE__INIT;
  *message = init_value;
}
size_t cast_channel__auth_challenge__get_packed_size
                     (const CastChannel__AuthChallenge *message)
{
  assert(message->base.descriptor == &cast_channel__auth_challenge__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cast_channel__auth_challenge__pack
                     (const CastChannel__AuthChallenge *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cast_channel__auth_challenge__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cast_channel__auth_challenge__pack_to_buffer
                     (const CastChannel__AuthChallenge *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cast_channel__auth_challenge__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CastChannel__AuthChallenge *
       cast_channel__auth_challenge__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CastChannel__AuthChallenge *)
     protobuf_c_message_unpack (&cast_channel__auth_challenge__descriptor,
                                allocator, len, data);
}
void   cast_channel__auth_challenge__free_unpacked
                     (CastChannel__AuthChallenge *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cast_channel__auth_challenge__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cast_channel__auth_response__init
                     (CastChannel__AuthResponse         *message)
{
  static const CastChannel__AuthResponse init_value = CAST_CHANNEL__AUTH_RESPONSE__INIT;
  *message = init_value;
}
size_t cast_channel__auth_response__get_packed_size
                     (const CastChannel__AuthResponse *message)
{
  assert(message->base.descriptor == &cast_channel__auth_response__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cast_channel__auth_response__pack
                     (const CastChannel__AuthResponse *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cast_channel__auth_response__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cast_channel__auth_response__pack_to_buffer
                     (const CastChannel__AuthResponse *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cast_channel__auth_response__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CastChannel__AuthResponse *
       cast_channel__auth_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CastChannel__AuthResponse *)
     protobuf_c_message_unpack (&cast_channel__auth_response__descriptor,
                                allocator, len, data);
}
void   cast_channel__auth_response__free_unpacked
                     (CastChannel__AuthResponse *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cast_channel__auth_response__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cast_channel__auth_error__init
                     (CastChannel__AuthError         *message)
{
  static const CastChannel__AuthError init_value = CAST_CHANNEL__AUTH_ERROR__INIT;
  *message = init_value;
}
size_t cast_channel__auth_error__get_packed_size
                     (const CastChannel__AuthError *message)
{
  assert(message->base.descriptor == &cast_channel__auth_error__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cast_channel__auth_error__pack
                     (const CastChannel__AuthError *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cast_channel__auth_error__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cast_channel__auth_error__pack_to_buffer
                     (const CastChannel__AuthError *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cast_channel__auth_error__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CastChannel__AuthError *
       cast_channel__auth_error__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CastChannel__AuthError *)
     protobuf_c_message_unpack (&cast_channel__auth_error__descriptor,
                                allocator, len, data);
}
void   cast_channel__auth_error__free_unpacked
                     (CastChannel__AuthError *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cast_channel__auth_error__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   cast_channel__device_auth_message__init
                     (CastChannel__DeviceAuthMessage         *message)
{
  static const CastChannel__DeviceAuthMessage init_value = CAST_CHANNEL__DEVICE_AUTH_MESSAGE__INIT;
  *message = init_value;
}
size_t cast_channel__device_auth_message__get_packed_size
                     (const CastChannel__DeviceAuthMessage *message)
{
  assert(message->base.descriptor == &cast_channel__device_auth_message__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t cast_channel__device_auth_message__pack
                     (const CastChannel__DeviceAuthMessage *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &cast_channel__device_auth_message__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t cast_channel__device_auth_message__pack_to_buffer
                     (const CastChannel__DeviceAuthMessage *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &cast_channel__device_auth_message__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
CastChannel__DeviceAuthMessage *
       cast_channel__device_auth_message__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (CastChannel__DeviceAuthMessage *)
     protobuf_c_message_unpack (&cast_channel__device_auth_message__descriptor,
                                allocator, len, data);
}
void   cast_channel__device_auth_message__free_unpacked
                     (CastChannel__DeviceAuthMessage *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &cast_channel__device_auth_message__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCEnumValue cast_channel__cast_message__protocol_version__enum_values_by_number[1] =
{
  { "CASTV2_1_0", "CAST_CHANNEL__CAST_MESSAGE__PROTOCOL_VERSION__CASTV2_1_0", 0 },
};
static const ProtobufCIntRange cast_channel__cast_message__protocol_version__value_ranges[] = {
{0, 0},{0, 1}
};
static const ProtobufCEnumValueIndex cast_channel__cast_message__protocol_version__enum_values_by_name[1] =
{
  { "CASTV2_1_0", 0 },
};
const ProtobufCEnumDescriptor cast_channel__cast_message__protocol_version__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "cast_channel.CastMessage.ProtocolVersion",
  "ProtocolVersion",
  "CastChannel__CastMessage__ProtocolVersion",
  "cast_channel",
  1,
  cast_channel__cast_message__protocol_version__enum_values_by_number,
  1,
  cast_channel__cast_message__protocol_version__enum_values_by_name,
  1,
  cast_channel__cast_message__protocol_version__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCEnumValue cast_channel__cast_message__payload_type__enum_values_by_number[2] =
{
  { "STRING", "CAST_CHANNEL__CAST_MESSAGE__PAYLOAD_TYPE__STRING", 0 },
  { "BINARY", "CAST_CHANNEL__CAST_MESSAGE__PAYLOAD_TYPE__BINARY", 1 },
};
static const ProtobufCIntRange cast_channel__cast_message__payload_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex cast_channel__cast_message__payload_type__enum_values_by_name[2] =
{
  { "BINARY", 1 },
  { "STRING", 0 },
};
const ProtobufCEnumDescriptor cast_channel__cast_message__payload_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "cast_channel.CastMessage.PayloadType",
  "PayloadType",
  "CastChannel__CastMessage__PayloadType",
  "cast_channel",
  2,
  cast_channel__cast_message__payload_type__enum_values_by_number,
  2,
  cast_channel__cast_message__payload_type__enum_values_by_name,
  1,
  cast_channel__cast_message__payload_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor cast_channel__cast_message__field_descriptors[7] =
{
  {
    "protocol_version",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CastChannel__CastMessage, protocol_version),
    &cast_channel__cast_message__protocol_version__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "source_id",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CastChannel__CastMessage, source_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "destination_id",
    3,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CastChannel__CastMessage, destination_id),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "namespace",
    4,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CastChannel__CastMessage, namespace_),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_type",
    5,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CastChannel__CastMessage, payload_type),
    &cast_channel__cast_message__payload_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_utf8",
    6,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_STRING,
    0,   /* quantifier_offset */
    offsetof(CastChannel__CastMessage, payload_utf8),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "payload_binary",
    7,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CastChannel__CastMessage, has_payload_binary),
    offsetof(CastChannel__CastMessage, payload_binary),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cast_channel__cast_message__field_indices_by_name[] = {
  2,   /* field[2] = destination_id */
  3,   /* field[3] = namespace */
  6,   /* field[6] = payload_binary */
  4,   /* field[4] = payload_type */
  5,   /* field[5] = payload_utf8 */
  0,   /* field[0] = protocol_version */
  1,   /* field[1] = source_id */
};
static const ProtobufCIntRange cast_channel__cast_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 7 }
};
const ProtobufCMessageDescriptor cast_channel__cast_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cast_channel.CastMessage",
  "CastMessage",
  "CastChannel__CastMessage",
  "cast_channel",
  sizeof(CastChannel__CastMessage),
  7,
  cast_channel__cast_message__field_descriptors,
  cast_channel__cast_message__field_indices_by_name,
  1,  cast_channel__cast_message__number_ranges,
  (ProtobufCMessageInit) cast_channel__cast_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
#define cast_channel__auth_challenge__field_descriptors NULL
#define cast_channel__auth_challenge__field_indices_by_name NULL
#define cast_channel__auth_challenge__number_ranges NULL
const ProtobufCMessageDescriptor cast_channel__auth_challenge__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cast_channel.AuthChallenge",
  "AuthChallenge",
  "CastChannel__AuthChallenge",
  "cast_channel",
  sizeof(CastChannel__AuthChallenge),
  0,
  cast_channel__auth_challenge__field_descriptors,
  cast_channel__auth_challenge__field_indices_by_name,
  0,  cast_channel__auth_challenge__number_ranges,
  (ProtobufCMessageInit) cast_channel__auth_challenge__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cast_channel__auth_response__field_descriptors[3] =
{
  {
    "signature",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CastChannel__AuthResponse, signature),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_auth_certificate",
    2,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_BYTES,
    0,   /* quantifier_offset */
    offsetof(CastChannel__AuthResponse, client_auth_certificate),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "client_ca",
    3,
    PROTOBUF_C_LABEL_REPEATED,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(CastChannel__AuthResponse, n_client_ca),
    offsetof(CastChannel__AuthResponse, client_ca),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cast_channel__auth_response__field_indices_by_name[] = {
  1,   /* field[1] = client_auth_certificate */
  2,   /* field[2] = client_ca */
  0,   /* field[0] = signature */
};
static const ProtobufCIntRange cast_channel__auth_response__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cast_channel__auth_response__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cast_channel.AuthResponse",
  "AuthResponse",
  "CastChannel__AuthResponse",
  "cast_channel",
  sizeof(CastChannel__AuthResponse),
  3,
  cast_channel__auth_response__field_descriptors,
  cast_channel__auth_response__field_indices_by_name,
  1,  cast_channel__auth_response__number_ranges,
  (ProtobufCMessageInit) cast_channel__auth_response__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCEnumValue cast_channel__auth_error__error_type__enum_values_by_number[2] =
{
  { "INTERNAL_ERROR", "CAST_CHANNEL__AUTH_ERROR__ERROR_TYPE__INTERNAL_ERROR", 0 },
  { "NO_TLS", "CAST_CHANNEL__AUTH_ERROR__ERROR_TYPE__NO_TLS", 1 },
};
static const ProtobufCIntRange cast_channel__auth_error__error_type__value_ranges[] = {
{0, 0},{0, 2}
};
static const ProtobufCEnumValueIndex cast_channel__auth_error__error_type__enum_values_by_name[2] =
{
  { "INTERNAL_ERROR", 0 },
  { "NO_TLS", 1 },
};
const ProtobufCEnumDescriptor cast_channel__auth_error__error_type__descriptor =
{
  PROTOBUF_C__ENUM_DESCRIPTOR_MAGIC,
  "cast_channel.AuthError.ErrorType",
  "ErrorType",
  "CastChannel__AuthError__ErrorType",
  "cast_channel",
  2,
  cast_channel__auth_error__error_type__enum_values_by_number,
  2,
  cast_channel__auth_error__error_type__enum_values_by_name,
  1,
  cast_channel__auth_error__error_type__value_ranges,
  NULL,NULL,NULL,NULL   /* reserved[1234] */
};
static const ProtobufCFieldDescriptor cast_channel__auth_error__field_descriptors[1] =
{
  {
    "error_type",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_ENUM,
    0,   /* quantifier_offset */
    offsetof(CastChannel__AuthError, error_type),
    &cast_channel__auth_error__error_type__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cast_channel__auth_error__field_indices_by_name[] = {
  0,   /* field[0] = error_type */
};
static const ProtobufCIntRange cast_channel__auth_error__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor cast_channel__auth_error__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cast_channel.AuthError",
  "AuthError",
  "CastChannel__AuthError",
  "cast_channel",
  sizeof(CastChannel__AuthError),
  1,
  cast_channel__auth_error__field_descriptors,
  cast_channel__auth_error__field_indices_by_name,
  1,  cast_channel__auth_error__number_ranges,
  (ProtobufCMessageInit) cast_channel__auth_error__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor cast_channel__device_auth_message__field_descriptors[3] =
{
  {
    "challenge",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CastChannel__DeviceAuthMessage, challenge),
    &cast_channel__auth_challenge__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "response",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CastChannel__DeviceAuthMessage, response),
    &cast_channel__auth_response__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "error",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_MESSAGE,
    0,   /* quantifier_offset */
    offsetof(CastChannel__DeviceAuthMessage, error),
    &cast_channel__auth_error__descriptor,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned cast_channel__device_auth_message__field_indices_by_name[] = {
  0,   /* field[0] = challenge */
  2,   /* field[2] = error */
  1,   /* field[1] = response */
};
static const ProtobufCIntRange cast_channel__device_auth_message__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor cast_channel__device_auth_message__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "cast_channel.DeviceAuthMessage",
  "DeviceAuthMessage",
  "CastChannel__DeviceAuthMessage",
  "cast_channel",
  sizeof(CastChannel__DeviceAuthMessage),
  3,
  cast_channel__device_auth_message__field_descriptors,
  cast_channel__device_auth_message__field_indices_by_name,
  1,  cast_channel__device_auth_message__number_ranges,
  (ProtobufCMessageInit) cast_channel__device_auth_message__init,
  NULL,NULL,NULL    /* reserved[123] */
};
